// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: case_article.proto

package cases

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaseArticles_ListCaseArticles_FullMethodName  = "/webitel.cases.CaseArticles/ListCaseArticles"
	CaseArticles_LinkCaseArticle_FullMethodName   = "/webitel.cases.CaseArticles/LinkCaseArticle"
	CaseArticles_UnlinkCaseArticle_FullMethodName = "/webitel.cases.CaseArticles/UnlinkCaseArticle"
	CaseArticles_ListArticleCases_FullMethodName  = "/webitel.cases.CaseArticles/ListArticleCases"
)

// CaseArticlesClient is the client API for CaseArticles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaseArticlesClient interface {
	// Articles of a case, the close article first.
	ListCaseArticles(ctx context.Context, in *ListCaseArticlesRequest, opts ...grpc.CallOption) (*CaseArticleList, error)
	// Links an article to a case; linking it again returns the same link.
	LinkCaseArticle(ctx context.Context, in *LinkCaseArticleRequest, opts ...grpc.CallOption) (*CaseArticle, error)
	// Removes a manual link; the close article is changed on the case itself.
	UnlinkCaseArticle(ctx context.Context, in *UnlinkCaseArticleRequest, opts ...grpc.CallOption) (*CaseArticle, error)
	// Cases of an article the user can read.
	ListArticleCases(ctx context.Context, in *ListArticleCasesRequest, opts ...grpc.CallOption) (*CaseArticleList, error)
}

type caseArticlesClient struct {
	cc grpc.ClientConnInterface
}

func NewCaseArticlesClient(cc grpc.ClientConnInterface) CaseArticlesClient {
	return &caseArticlesClient{cc}
}

func (c *caseArticlesClient) ListCaseArticles(ctx context.Context, in *ListCaseArticlesRequest, opts ...grpc.CallOption) (*CaseArticleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaseArticleList)
	err := c.cc.Invoke(ctx, CaseArticles_ListCaseArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseArticlesClient) LinkCaseArticle(ctx context.Context, in *LinkCaseArticleRequest, opts ...grpc.CallOption) (*CaseArticle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaseArticle)
	err := c.cc.Invoke(ctx, CaseArticles_LinkCaseArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseArticlesClient) UnlinkCaseArticle(ctx context.Context, in *UnlinkCaseArticleRequest, opts ...grpc.CallOption) (*CaseArticle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaseArticle)
	err := c.cc.Invoke(ctx, CaseArticles_UnlinkCaseArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseArticlesClient) ListArticleCases(ctx context.Context, in *ListArticleCasesRequest, opts ...grpc.CallOption) (*CaseArticleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaseArticleList)
	err := c.cc.Invoke(ctx, CaseArticles_ListArticleCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaseArticlesServer is the server API for CaseArticles service.
// All implementations must embed UnimplementedCaseArticlesServer
// for forward compatibility.
type CaseArticlesServer interface {
	// Articles of a case, the close article first.
	ListCaseArticles(context.Context, *ListCaseArticlesRequest) (*CaseArticleList, error)
	// Links an article to a case; linking it again returns the same link.
	LinkCaseArticle(context.Context, *LinkCaseArticleRequest) (*CaseArticle, error)
	// Removes a manual link; the close article is changed on the case itself.
	UnlinkCaseArticle(context.Context, *UnlinkCaseArticleRequest) (*CaseArticle, error)
	// Cases of an article the user can read.
	ListArticleCases(context.Context, *ListArticleCasesRequest) (*CaseArticleList, error)
	mustEmbedUnimplementedCaseArticlesServer()
}

// UnimplementedCaseArticlesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaseArticlesServer struct{}

func (UnimplementedCaseArticlesServer) ListCaseArticles(context.Context, *ListCaseArticlesRequest) (*CaseArticleList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCaseArticles not implemented")
}
func (UnimplementedCaseArticlesServer) LinkCaseArticle(context.Context, *LinkCaseArticleRequest) (*CaseArticle, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkCaseArticle not implemented")
}
func (UnimplementedCaseArticlesServer) UnlinkCaseArticle(context.Context, *UnlinkCaseArticleRequest) (*CaseArticle, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkCaseArticle not implemented")
}
func (UnimplementedCaseArticlesServer) ListArticleCases(context.Context, *ListArticleCasesRequest) (*CaseArticleList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArticleCases not implemented")
}
func (UnimplementedCaseArticlesServer) mustEmbedUnimplementedCaseArticlesServer() {}
func (UnimplementedCaseArticlesServer) testEmbeddedByValue()                      {}

// UnsafeCaseArticlesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaseArticlesServer will
// result in compilation errors.
type UnsafeCaseArticlesServer interface {
	mustEmbedUnimplementedCaseArticlesServer()
}

func RegisterCaseArticlesServer(s grpc.ServiceRegistrar, srv CaseArticlesServer) {
	// If the following call panics, it indicates UnimplementedCaseArticlesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaseArticles_ServiceDesc, srv)
}

func _CaseArticles_ListCaseArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCaseArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseArticlesServer).ListCaseArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseArticles_ListCaseArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseArticlesServer).ListCaseArticles(ctx, req.(*ListCaseArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseArticles_LinkCaseArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkCaseArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseArticlesServer).LinkCaseArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseArticles_LinkCaseArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseArticlesServer).LinkCaseArticle(ctx, req.(*LinkCaseArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseArticles_UnlinkCaseArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkCaseArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseArticlesServer).UnlinkCaseArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseArticles_UnlinkCaseArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseArticlesServer).UnlinkCaseArticle(ctx, req.(*UnlinkCaseArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseArticles_ListArticleCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticleCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseArticlesServer).ListArticleCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseArticles_ListArticleCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseArticlesServer).ListArticleCases(ctx, req.(*ListArticleCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaseArticles_ServiceDesc is the grpc.ServiceDesc for CaseArticles service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaseArticles_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webitel.cases.CaseArticles",
	HandlerType: (*CaseArticlesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCaseArticles",
			Handler:    _CaseArticles_ListCaseArticles_Handler,
		},
		{
			MethodName: "LinkCaseArticle",
			Handler:    _CaseArticles_LinkCaseArticle_Handler,
		},
		{
			MethodName: "UnlinkCaseArticle",
			Handler:    _CaseArticles_UnlinkCaseArticle_Handler,
		},
		{
			MethodName: "ListArticleCases",
			Handler:    _CaseArticles_ListArticleCases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "case_article.proto",
}
