// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: case_article.proto

package cases

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How a knowledge base article got linked to a case.
type CaseArticleSource int32

const (
	CaseArticleSource_CASE_ARTICLE_SOURCE_UNSPECIFIED CaseArticleSource = 0
	// Linked by an operator.
	CaseArticleSource_CASE_ARTICLE_SOURCE_MANUAL CaseArticleSource = 1
	// The close article of the case.
	CaseArticleSource_CASE_ARTICLE_SOURCE_RESOLUTION CaseArticleSource = 2
)

// Enum value maps for CaseArticleSource.
var (
	CaseArticleSource_name = map[int32]string{
		0: "CASE_ARTICLE_SOURCE_UNSPECIFIED",
		1: "CASE_ARTICLE_SOURCE_MANUAL",
		2: "CASE_ARTICLE_SOURCE_RESOLUTION",
	}
	CaseArticleSource_value = map[string]int32{
		"CASE_ARTICLE_SOURCE_UNSPECIFIED": 0,
		"CASE_ARTICLE_SOURCE_MANUAL":      1,
		"CASE_ARTICLE_SOURCE_RESOLUTION":  2,
	}
)

func (x CaseArticleSource) Enum() *CaseArticleSource {
	p := new(CaseArticleSource)
	*p = x
	return p
}

func (x CaseArticleSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseArticleSource) Descriptor() protoreflect.EnumDescriptor {
	return file_case_article_proto_enumTypes[0].Descriptor()
}

func (CaseArticleSource) Type() protoreflect.EnumType {
	return &file_case_article_proto_enumTypes[0]
}

func (x CaseArticleSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseArticleSource.Descriptor instead.
func (CaseArticleSource) EnumDescriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{0}
}

// Knowledge base article linked to a case.
type CaseArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Knowledge base article; id only.
	Article *Lookup `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	// Linked case; set on the article side.
	Case   *RelatedCaseLookup `protobuf:"bytes,2,opt,name=case,proto3" json:"case,omitempty"`
	Source CaseArticleSource  `protobuf:"varint,3,opt,name=source,proto3,enum=webitel.cases.CaseArticleSource" json:"source,omitempty"`
	// Empty for the close article.
	CreatedBy *Lookup `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Unixmilli; empty for the close article.
	CreatedAt     int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseArticle) Reset() {
	*x = CaseArticle{}
	mi := &file_case_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseArticle) ProtoMessage() {}

func (x *CaseArticle) ProtoReflect() protoreflect.Message {
	mi := &file_case_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseArticle.ProtoReflect.Descriptor instead.
func (*CaseArticle) Descriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{0}
}

func (x *CaseArticle) GetArticle() *Lookup {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *CaseArticle) GetCase() *RelatedCaseLookup {
	if x != nil {
		return x.Case
	}
	return nil
}

func (x *CaseArticle) GetSource() CaseArticleSource {
	if x != nil {
		return x.Source
	}
	return CaseArticleSource_CASE_ARTICLE_SOURCE_UNSPECIFIED
}

func (x *CaseArticle) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *CaseArticle) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type InputCaseArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Knowledge base article to link.
	Article       *Lookup `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputCaseArticle) Reset() {
	*x = InputCaseArticle{}
	mi := &file_case_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputCaseArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputCaseArticle) ProtoMessage() {}

func (x *InputCaseArticle) ProtoReflect() protoreflect.Message {
	mi := &file_case_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputCaseArticle.ProtoReflect.Descriptor instead.
func (*InputCaseArticle) Descriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{1}
}

func (x *InputCaseArticle) GetArticle() *Lookup {
	if x != nil {
		return x.Article
	}
	return nil
}

type CaseArticleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Next          bool                   `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*CaseArticle         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseArticleList) Reset() {
	*x = CaseArticleList{}
	mi := &file_case_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseArticleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseArticleList) ProtoMessage() {}

func (x *CaseArticleList) ProtoReflect() protoreflect.Message {
	mi := &file_case_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseArticleList.ProtoReflect.Descriptor instead.
func (*CaseArticleList) Descriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{2}
}

func (x *CaseArticleList) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CaseArticleList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *CaseArticleList) GetItems() []*CaseArticle {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCaseArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseEtag      string                 `protobuf:"bytes,1,opt,name=case_etag,json=caseEtag,proto3" json:"case_etag,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaseArticlesRequest) Reset() {
	*x = ListCaseArticlesRequest{}
	mi := &file_case_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaseArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaseArticlesRequest) ProtoMessage() {}

func (x *ListCaseArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaseArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListCaseArticlesRequest) Descriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{3}
}

func (x *ListCaseArticlesRequest) GetCaseEtag() string {
	if x != nil {
		return x.CaseEtag
	}
	return ""
}

func (x *ListCaseArticlesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCaseArticlesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LinkCaseArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseEtag      string                 `protobuf:"bytes,1,opt,name=case_etag,json=caseEtag,proto3" json:"case_etag,omitempty"`
	Input         *InputCaseArticle      `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkCaseArticleRequest) Reset() {
	*x = LinkCaseArticleRequest{}
	mi := &file_case_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCaseArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCaseArticleRequest) ProtoMessage() {}

func (x *LinkCaseArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCaseArticleRequest.ProtoReflect.Descriptor instead.
func (*LinkCaseArticleRequest) Descriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{4}
}

func (x *LinkCaseArticleRequest) GetCaseEtag() string {
	if x != nil {
		return x.CaseEtag
	}
	return ""
}

func (x *LinkCaseArticleRequest) GetInput() *InputCaseArticle {
	if x != nil {
		return x.Input
	}
	return nil
}

type UnlinkCaseArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseEtag      string                 `protobuf:"bytes,1,opt,name=case_etag,json=caseEtag,proto3" json:"case_etag,omitempty"`
	ArticleId     int64                  `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkCaseArticleRequest) Reset() {
	*x = UnlinkCaseArticleRequest{}
	mi := &file_case_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkCaseArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkCaseArticleRequest) ProtoMessage() {}

func (x *UnlinkCaseArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkCaseArticleRequest.ProtoReflect.Descriptor instead.
func (*UnlinkCaseArticleRequest) Descriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{5}
}

func (x *UnlinkCaseArticleRequest) GetCaseEtag() string {
	if x != nil {
		return x.CaseEtag
	}
	return ""
}

func (x *UnlinkCaseArticleRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ListArticleCasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleCasesRequest) Reset() {
	*x = ListArticleCasesRequest{}
	mi := &file_case_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleCasesRequest) ProtoMessage() {}

func (x *ListArticleCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleCasesRequest.ProtoReflect.Descriptor instead.
func (*ListArticleCasesRequest) Descriptor() ([]byte, []int) {
	return file_case_article_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticleCasesRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ListArticleCasesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticleCasesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_case_article_proto protoreflect.FileDescriptor

const file_case_article_proto_rawDesc = "" +
	"\n" +
	"\x12case_article.proto\x12\rwebitel.cases\x1a\rgeneral.proto\x1a\x12related_case.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xf7\x01\n" +
	"\vCaseArticle\x12)\n" +
	"\aarticle\x18\x01 \x01(\v2\x0f.general.LookupR\aarticle\x124\n" +
	"\x04case\x18\x02 \x01(\v2 .webitel.cases.RelatedCaseLookupR\x04case\x128\n" +
	"\x06source\x18\x03 \x01(\x0e2 .webitel.cases.CaseArticleSourceR\x06source\x12.\n" +
	"\n" +
	"created_by\x18\x04 \x01(\v2\x0f.general.LookupR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"=\n" +
	"\x10InputCaseArticle\x12)\n" +
	"\aarticle\x18\x01 \x01(\v2\x0f.general.LookupR\aarticle\"k\n" +
	"\x0fCaseArticleList\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\x120\n" +
	"\x05items\x18\x03 \x03(\v2\x1a.webitel.cases.CaseArticleR\x05items\"^\n" +
	"\x17ListCaseArticlesRequest\x12\x1b\n" +
	"\tcase_etag\x18\x01 \x01(\tR\bcaseEtag\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"l\n" +
	"\x16LinkCaseArticleRequest\x12\x1b\n" +
	"\tcase_etag\x18\x01 \x01(\tR\bcaseEtag\x125\n" +
	"\x05input\x18\x02 \x01(\v2\x1f.webitel.cases.InputCaseArticleR\x05input\"V\n" +
	"\x18UnlinkCaseArticleRequest\x12\x1b\n" +
	"\tcase_etag\x18\x01 \x01(\tR\bcaseEtag\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\"`\n" +
	"\x17ListArticleCasesRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size*|\n" +
	"\x11CaseArticleSource\x12#\n" +
	"\x1fCASE_ARTICLE_SOURCE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCASE_ARTICLE_SOURCE_MANUAL\x10\x01\x12\"\n" +
	"\x1eCASE_ARTICLE_SOURCE_RESOLUTION\x10\x022\xc4\x04\n" +
	"\fCaseArticles\x12\x83\x01\n" +
	"\x10ListCaseArticles\x12&.webitel.cases.ListCaseArticlesRequest\x1a\x1e.webitel.cases.CaseArticleList\"'\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1d\x12\x1b/cases/{case_etag}/articles\x12\x84\x01\n" +
	"\x0fLinkCaseArticle\x12%.webitel.cases.LinkCaseArticleRequest\x1a\x1a.webitel.cases.CaseArticle\".\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02$:\x05input\"\x1b/cases/{case_etag}/articles\x12\x8e\x01\n" +
	"\x11UnlinkCaseArticle\x12'.webitel.cases.UnlinkCaseArticleRequest\x1a\x1a.webitel.cases.CaseArticle\"4\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02**(/cases/{case_etag}/articles/{article_id}\x12\x8a\x01\n" +
	"\x10ListArticleCases\x12&.webitel.cases.ListArticleCasesRequest\x1a\x1e.webitel.cases.CaseArticleList\".\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02$\x12\"/cases/articles/{article_id}/cases\x1a\t\x8a\xb5\x18\x05casesB\xa4\x01\n" +
	"\x11com.webitel.casesB\x10CaseArticleProtoP\x01Z(github.com/webitel/cases/api/cases;cases\xa2\x02\x03WCX\xaa\x02\rWebitel.Cases\xca\x02\rWebitel\\Cases\xe2\x02\x19Webitel\\Cases\\GPBMetadata\xea\x02\x0eWebitel::Casesb\x06proto3"

var (
	file_case_article_proto_rawDescOnce sync.Once
	file_case_article_proto_rawDescData []byte
)

func file_case_article_proto_rawDescGZIP() []byte {
	file_case_article_proto_rawDescOnce.Do(func() {
		file_case_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_case_article_proto_rawDesc), len(file_case_article_proto_rawDesc)))
	})
	return file_case_article_proto_rawDescData
}

var file_case_article_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_case_article_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_case_article_proto_goTypes = []any{
	(CaseArticleSource)(0),           // 0: webitel.cases.CaseArticleSource
	(*CaseArticle)(nil),              // 1: webitel.cases.CaseArticle
	(*InputCaseArticle)(nil),         // 2: webitel.cases.InputCaseArticle
	(*CaseArticleList)(nil),          // 3: webitel.cases.CaseArticleList
	(*ListCaseArticlesRequest)(nil),  // 4: webitel.cases.ListCaseArticlesRequest
	(*LinkCaseArticleRequest)(nil),   // 5: webitel.cases.LinkCaseArticleRequest
	(*UnlinkCaseArticleRequest)(nil), // 6: webitel.cases.UnlinkCaseArticleRequest
	(*ListArticleCasesRequest)(nil),  // 7: webitel.cases.ListArticleCasesRequest
	(*Lookup)(nil),                   // 8: general.Lookup
	(*RelatedCaseLookup)(nil),        // 9: webitel.cases.RelatedCaseLookup
}
var file_case_article_proto_depIdxs = []int32{
	8,  // 0: webitel.cases.CaseArticle.article:type_name -> general.Lookup
	9,  // 1: webitel.cases.CaseArticle.case:type_name -> webitel.cases.RelatedCaseLookup
	0,  // 2: webitel.cases.CaseArticle.source:type_name -> webitel.cases.CaseArticleSource
	8,  // 3: webitel.cases.CaseArticle.created_by:type_name -> general.Lookup
	8,  // 4: webitel.cases.InputCaseArticle.article:type_name -> general.Lookup
	1,  // 5: webitel.cases.CaseArticleList.items:type_name -> webitel.cases.CaseArticle
	2,  // 6: webitel.cases.LinkCaseArticleRequest.input:type_name -> webitel.cases.InputCaseArticle
	4,  // 7: webitel.cases.CaseArticles.ListCaseArticles:input_type -> webitel.cases.ListCaseArticlesRequest
	5,  // 8: webitel.cases.CaseArticles.LinkCaseArticle:input_type -> webitel.cases.LinkCaseArticleRequest
	6,  // 9: webitel.cases.CaseArticles.UnlinkCaseArticle:input_type -> webitel.cases.UnlinkCaseArticleRequest
	7,  // 10: webitel.cases.CaseArticles.ListArticleCases:input_type -> webitel.cases.ListArticleCasesRequest
	3,  // 11: webitel.cases.CaseArticles.ListCaseArticles:output_type -> webitel.cases.CaseArticleList
	1,  // 12: webitel.cases.CaseArticles.LinkCaseArticle:output_type -> webitel.cases.CaseArticle
	1,  // 13: webitel.cases.CaseArticles.UnlinkCaseArticle:output_type -> webitel.cases.CaseArticle
	3,  // 14: webitel.cases.CaseArticles.ListArticleCases:output_type -> webitel.cases.CaseArticleList
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_case_article_proto_init() }
func file_case_article_proto_init() {
	if File_case_article_proto != nil {
		return
	}
	file_general_proto_init()
	file_related_case_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_case_article_proto_rawDesc), len(file_case_article_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_case_article_proto_goTypes,
		DependencyIndexes: file_case_article_proto_depIdxs,
		EnumInfos:         file_case_article_proto_enumTypes,
		MessageInfos:      file_case_article_proto_msgTypes,
	}.Build()
	File_case_article_proto = out.File
	file_case_article_proto_goTypes = nil
	file_case_article_proto_depIdxs = nil
}
