// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: case_file.proto

package cases

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contains a list of case files with pagination.
type CaseFileList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current page number.
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Indicator if there is a next page.
	Next bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	// List of case files.
	Items         []*File `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseFileList) Reset() {
	*x = CaseFileList{}
	mi := &file_case_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseFileList) ProtoMessage() {}

func (x *CaseFileList) ProtoReflect() protoreflect.Message {
	mi := &file_case_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseFileList.ProtoReflect.Descriptor instead.
func (*CaseFileList) Descriptor() ([]byte, []int) {
	return file_case_file_proto_rawDescGZIP(), []int{0}
}

func (x *CaseFileList) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CaseFileList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *CaseFileList) GetItems() []*File {
	if x != nil {
		return x.Items
	}
	return nil
}

// Metadata for a file associated with a case.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage file ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Creator of the file.
	CreatedBy *ExtendedLookup `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Creation timestamp in Unix milliseconds.
	CreatedAt int64 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// File size in bytes.
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// MIME type of the file.
	Mime string `protobuf:"bytes,5,opt,name=mime,proto3" json:"mime,omitempty"`
	// File name.
	Name          string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Url           string `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Source        string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_case_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_case_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_case_file_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *File) GetCreatedBy() *ExtendedLookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *File) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Request message for deleting a file.
type DeleteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the file to delete.
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CaseEtag      string `protobuf:"bytes,2,opt,name=case_etag,json=caseEtag,proto3" json:"case_etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_case_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_case_file_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteFileRequest) GetCaseEtag() string {
	if x != nil {
		return x.CaseEtag
	}
	return ""
}

// Request message for listing files associated with a case.
type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the case to fetch files for (required).
	CaseEtag string `protobuf:"bytes,1,opt,name=case_etag,json=caseEtag,proto3" json:"case_etag,omitempty"`
	// The page number to retrieve.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of items per page.
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Search term.
	Q string `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	// Fields to include in the response.
	Fields []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	// Array of requested id.
	Ids []string `protobuf:"bytes,6,rep,name=ids,proto3" json:"ids,omitempty"`
	// Sorting
	Sort          string `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_case_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_case_file_proto_rawDescGZIP(), []int{3}
}

func (x *ListFilesRequest) GetCaseEtag() string {
	if x != nil {
		return x.CaseEtag
	}
	return ""
}

func (x *ListFilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFilesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListFilesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListFilesRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ListFilesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListFilesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

var File_case_file_proto protoreflect.FileDescriptor

const file_case_file_proto_rawDesc = "" +
	"\n" +
	"\x0fcase_file.proto\x12\rwebitel.cases\x1a\rgeneral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"a\n" +
	"\fCaseFileList\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\x12)\n" +
	"\x05items\x18\x03 \x03(\v2\x13.webitel.cases.FileR\x05items\"\xd3\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x126\n" +
	"\n" +
	"created_by\x18\x02 \x01(\v2\x17.general.ExtendedLookupR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mime\x18\x05 \x01(\tR\x04mime\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"L\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcase_etag\x18\x02 \x01(\tR\bcaseEtag:\n" +
	"\x92A\a\n" +
	"\x05\xd2\x01\x02id\"\xb6\x01\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tcase_etag\x18\x01 \x01(\tR\bcaseEtag\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x04 \x01(\tR\x01q\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\x12\x10\n" +
	"\x03ids\x18\x06 \x03(\tR\x03ids\x12\x12\n" +
	"\x04sort\x18\a \x01(\tR\x04sort:\x11\x92A\x0e\n" +
	"\f\xd2\x01\tcase_etag2\xbf\x02\n" +
	"\tCaseFiles\x12\xa3\x01\n" +
	"\tListFiles\x12\x1f.webitel.cases.ListFilesRequest\x1a\x1b.webitel.cases.CaseFileList\"X\x92A1\x12/Retrieve a list of files associated with a case\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1a\x12\x18/cases/{case_etag}/files\x12\x80\x01\n" +
	"\n" +
	"DeleteFile\x12 .webitel.cases.DeleteFileRequest\x1a\x13.webitel.cases.File\";\x92A\x0f\x12\rDelete a file\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x1f*\x1d/cases/{case_etag}/files/{id}\x1a\t\x8a\xb5\x18\x05casesB\xa1\x01\n" +
	"\x11com.webitel.casesB\rCaseFileProtoP\x01Z(github.com/webitel/cases/api/cases;cases\xa2\x02\x03WCX\xaa\x02\rWebitel.Cases\xca\x02\rWebitel\\Cases\xe2\x02\x19Webitel\\Cases\\GPBMetadata\xea\x02\x0eWebitel::Casesb\x06proto3"

var (
	file_case_file_proto_rawDescOnce sync.Once
	file_case_file_proto_rawDescData []byte
)

func file_case_file_proto_rawDescGZIP() []byte {
	file_case_file_proto_rawDescOnce.Do(func() {
		file_case_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_case_file_proto_rawDesc), len(file_case_file_proto_rawDesc)))
	})
	return file_case_file_proto_rawDescData
}

var file_case_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_case_file_proto_goTypes = []any{
	(*CaseFileList)(nil),      // 0: webitel.cases.CaseFileList
	(*File)(nil),              // 1: webitel.cases.File
	(*DeleteFileRequest)(nil), // 2: webitel.cases.DeleteFileRequest
	(*ListFilesRequest)(nil),  // 3: webitel.cases.ListFilesRequest
	(*ExtendedLookup)(nil),    // 4: general.ExtendedLookup
}
var file_case_file_proto_depIdxs = []int32{
	1, // 0: webitel.cases.CaseFileList.items:type_name -> webitel.cases.File
	4, // 1: webitel.cases.File.created_by:type_name -> general.ExtendedLookup
	3, // 2: webitel.cases.CaseFiles.ListFiles:input_type -> webitel.cases.ListFilesRequest
	2, // 3: webitel.cases.CaseFiles.DeleteFile:input_type -> webitel.cases.DeleteFileRequest
	0, // 4: webitel.cases.CaseFiles.ListFiles:output_type -> webitel.cases.CaseFileList
	1, // 5: webitel.cases.CaseFiles.DeleteFile:output_type -> webitel.cases.File
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_case_file_proto_init() }
func file_case_file_proto_init() {
	if File_case_file_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_case_file_proto_rawDesc), len(file_case_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_case_file_proto_goTypes,
		DependencyIndexes: file_case_file_proto_depIdxs,
		MessageInfos:      file_case_file_proto_msgTypes,
	}.Build()
	File_case_file_proto = out.File
	file_case_file_proto_goTypes = nil
	file_case_file_proto_depIdxs = nil
}
