// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: catalog.proto

package cases

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Catalog message represents the main catalog entity with metadata
type Catalog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the catalog
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the catalog
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the catalog (optional)
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Prefix used for case identification (optional)
	Prefix string `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Code for external integrations (optional)
	Code string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	// State of the catalog (true for active, false for inactive)
	State bool `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	// SLA associated with the catalog
	Sla *Lookup `protobuf:"bytes,7,opt,name=sla,proto3" json:"sla,omitempty"`
	// Status associated with the catalog
	Status *Lookup `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	// Close reason group associated with the catalog
	CloseReasonGroup *Lookup `protobuf:"bytes,9,opt,name=close_reason_group,json=closeReasonGroup,proto3" json:"close_reason_group,omitempty"`
	// Teams associated with the catalog
	Teams []*Lookup `protobuf:"bytes,11,rep,name=teams,proto3" json:"teams,omitempty"`
	// Skills associated with the catalog
	Skills []*Lookup `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	// Timestamp when the catalog was created
	CreatedAt int64 `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the catalog was last updated
	UpdatedAt int64 `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// User who created the catalog
	CreatedBy *Lookup `protobuf:"bytes,17,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// User who last updated the catalog
	UpdatedBy *Lookup `protobuf:"bytes,18,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// Service associated with the catalog
	Service []*Service `protobuf:"bytes,10,rep,name=service,proto3" json:"service,omitempty"`
	// flag showing whether the catalog was searched
	Searched      bool `protobuf:"varint,20,opt,name=searched,proto3" json:"searched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Catalog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Catalog) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Catalog) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Catalog) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *Catalog) GetSla() *Lookup {
	if x != nil {
		return x.Sla
	}
	return nil
}

func (x *Catalog) GetStatus() *Lookup {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Catalog) GetCloseReasonGroup() *Lookup {
	if x != nil {
		return x.CloseReasonGroup
	}
	return nil
}

func (x *Catalog) GetTeams() []*Lookup {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *Catalog) GetSkills() []*Lookup {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Catalog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Catalog) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Catalog) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Catalog) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *Catalog) GetService() []*Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Catalog) GetSearched() bool {
	if x != nil {
		return x.Searched
	}
	return false
}

// CatalogList message contains a list of catalogs with pagination
type CatalogList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page number for pagination
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Indicates if there are more pages
	Next bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	// List of catalog items
	Items         []*Catalog `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogList) Reset() {
	*x = CatalogList{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogList) ProtoMessage() {}

func (x *CatalogList) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogList.ProtoReflect.Descriptor instead.
func (*CatalogList) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CatalogList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CatalogList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *CatalogList) GetItems() []*Catalog {
	if x != nil {
		return x.Items
	}
	return nil
}

// InputCatalog message contains the fields for creating or updating a catalog
type InputCatalog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the catalog (required)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the catalog (optional)
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Prefix for case identification (optional)
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Code for external integrations (optional)
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// State of the catalog (true for active, false for inactive)
	State bool `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	// SLA ID associated with the catalog
	Sla *Lookup `protobuf:"bytes,6,opt,name=sla,proto3" json:"sla,omitempty"`
	// Status ID associated with the catalog
	Status *Lookup `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	// Close reason group ID associated with the catalog
	CloseReasonGroup *Lookup `protobuf:"bytes,8,opt,name=close_reason_group,json=closeReasonGroup,proto3" json:"close_reason_group,omitempty"`
	// List of team IDs associated with the catalog
	Teams []*Lookup `protobuf:"bytes,10,rep,name=teams,proto3" json:"teams,omitempty"`
	// List of skill IDs associated with the catalog
	Skills        []*Lookup `protobuf:"bytes,11,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputCatalog) Reset() {
	*x = InputCatalog{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputCatalog) ProtoMessage() {}

func (x *InputCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputCatalog.ProtoReflect.Descriptor instead.
func (*InputCatalog) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *InputCatalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputCatalog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InputCatalog) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *InputCatalog) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InputCatalog) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *InputCatalog) GetSla() *Lookup {
	if x != nil {
		return x.Sla
	}
	return nil
}

func (x *InputCatalog) GetStatus() *Lookup {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InputCatalog) GetCloseReasonGroup() *Lookup {
	if x != nil {
		return x.CloseReasonGroup
	}
	return nil
}

func (x *InputCatalog) GetTeams() []*Lookup {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *InputCatalog) GetSkills() []*Lookup {
	if x != nil {
		return x.Skills
	}
	return nil
}

// CreateCatalogRequest message for creating a new catalog
type CreateCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *InputCatalog          `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogRequest) Reset() {
	*x = CreateCatalogRequest{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogRequest) ProtoMessage() {}

func (x *CreateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogRequest.ProtoReflect.Descriptor instead.
func (*CreateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCatalogRequest) GetInput() *InputCatalog {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateCatalogRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// UpdateCatalogRequest message for updating an existing catalog
type UpdateCatalogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the catalog to be updated
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Input data for updating the catalog
	Input  *InputCatalog `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Fields []string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// ---- JSON PATCH fields mask ----
	XJsonMask     []string `protobuf:"bytes,4,rep,name=x_json_mask,json=xJsonMask,proto3" json:"x_json_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatalogRequest) Reset() {
	*x = UpdateCatalogRequest{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogRequest) ProtoMessage() {}

func (x *UpdateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCatalogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCatalogRequest) GetInput() *InputCatalog {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *UpdateCatalogRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateCatalogRequest) GetXJsonMask() []string {
	if x != nil {
		return x.XJsonMask
	}
	return nil
}

// DeleteCatalogRequest message for deleting a catalog
type DeleteCatalogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the catalog to be deleted
	Id            []int64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogRequest) Reset() {
	*x = DeleteCatalogRequest{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogRequest) ProtoMessage() {}

func (x *DeleteCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCatalogRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

// ListCatalogRequest message for listing catalogs
type ListCatalogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page number for pagination
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Number of records per page
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Fields to be retrieved as a result.
	// If the user passes "-" as the value for fields,
	// it will retrieve all available fields for each catalog.
	Fields []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Sorting options by fields
	Sort string `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	// List of IDs to filter the catalogs
	Id []int64 `protobuf:"varint,5,rep,packed,name=id,proto3" json:"id,omitempty"`
	// Search query string for filtering by name. Supports:
	// - Wildcards (*) for substring matching
	// - Placeholder (?) for single character substitution
	// - Exact match for full names
	Query string `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	// Filter by state (true for active, false for inactive)
	State bool `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	// Filter by the depth of the hierarchy to retrieve services.
	// The depth indicates how many ancestor levels of services
	// will be included for each catalog.
	//   - A depth of 0 includes only the direct catalog.
	//   - A depth of 1 includes the catalog and its immediate services.
	//   - By default the depth is limited by 3,
	//     meaning all nested services and sub-services will be included.
	Depth int64 `protobuf:"varint,8,opt,name=depth,proto3" json:"depth,omitempty"`
	// Fields to be retrieved as a result for [SUBSERVICES].
	// If the user passes "-" as the value for fields,
	// it will retrieve all available fields for each catalog subservices.
	SubFields []string `protobuf:"bytes,9,rep,name=sub_fields,json=subFields,proto3" json:"sub_fields,omitempty"`
	// Filter catalogs with subservices
	HasSubservices bool `protobuf:"varint,10,opt,name=hasSubservices,proto3" json:"hasSubservices,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCatalogRequest) Reset() {
	*x = ListCatalogRequest{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogRequest) ProtoMessage() {}

func (x *ListCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListCatalogRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCatalogRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListCatalogRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ListCatalogRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListCatalogRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListCatalogRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListCatalogRequest) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *ListCatalogRequest) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *ListCatalogRequest) GetSubFields() []string {
	if x != nil {
		return x.SubFields
	}
	return nil
}

func (x *ListCatalogRequest) GetHasSubservices() bool {
	if x != nil {
		return x.HasSubservices
	}
	return false
}

// LocateCatalogRequest message for locating a specific catalog by ID
type LocateCatalogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the catalog to be located
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Fields to be retrieved as a result.
	// If the user passes "-" as the value for fields,
	// it will retrieve all available fields for each catalog.
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// Fields to be retrieved as a result for [SUBSERVICES].
	// If the user passes "-" as the value for fields,
	// it will retrieve all available fields for each catalog subservices.
	SubFields     []string `protobuf:"bytes,3,rep,name=sub_fields,json=subFields,proto3" json:"sub_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateCatalogRequest) Reset() {
	*x = LocateCatalogRequest{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateCatalogRequest) ProtoMessage() {}

func (x *LocateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateCatalogRequest.ProtoReflect.Descriptor instead.
func (*LocateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *LocateCatalogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LocateCatalogRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LocateCatalogRequest) GetSubFields() []string {
	if x != nil {
		return x.SubFields
	}
	return nil
}

// LocateCatalogResponse message contains a single catalog entity
type LocateCatalogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The located catalog
	Catalog       *Catalog `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateCatalogResponse) Reset() {
	*x = LocateCatalogResponse{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateCatalogResponse) ProtoMessage() {}

func (x *LocateCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateCatalogResponse.ProtoReflect.Descriptor instead.
func (*LocateCatalogResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *LocateCatalogResponse) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\rwebitel.cases\x1a\rgeneral.proto\x1a\rservice.proto\x1a\x1bgoogle/api/visibility.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xd8\x04\n" +
	"\aCatalog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x06 \x01(\bR\x05state\x12!\n" +
	"\x03sla\x18\a \x01(\v2\x0f.general.LookupR\x03sla\x12'\n" +
	"\x06status\x18\b \x01(\v2\x0f.general.LookupR\x06status\x12=\n" +
	"\x12close_reason_group\x18\t \x01(\v2\x0f.general.LookupR\x10closeReasonGroup\x12%\n" +
	"\x05teams\x18\v \x03(\v2\x0f.general.LookupR\x05teams\x12'\n" +
	"\x06skills\x18\f \x03(\v2\x0f.general.LookupR\x06skills\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\x03R\tupdatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x11 \x01(\v2\x0f.general.LookupR\tcreatedBy\x12.\n" +
	"\n" +
	"updated_by\x18\x12 \x01(\v2\x0f.general.LookupR\tupdatedBy\x120\n" +
	"\aservice\x18\n" +
	" \x03(\v2\x16.webitel.cases.ServiceR\aservice\x12\x1a\n" +
	"\bsearched\x18\x14 \x01(\bR\bsearched\"c\n" +
	"\vCatalogList\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\x12,\n" +
	"\x05items\x18\x03 \x03(\v2\x16.webitel.cases.CatalogR\x05items\"\xe1\x02\n" +
	"\fInputCatalog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x05 \x01(\bR\x05state\x12!\n" +
	"\x03sla\x18\x06 \x01(\v2\x0f.general.LookupR\x03sla\x12'\n" +
	"\x06status\x18\a \x01(\v2\x0f.general.LookupR\x06status\x12=\n" +
	"\x12close_reason_group\x18\b \x01(\v2\x0f.general.LookupR\x10closeReasonGroup\x12%\n" +
	"\x05teams\x18\n" +
	" \x03(\v2\x0f.general.LookupR\x05teams\x12'\n" +
	"\x06skills\x18\v \x03(\v2\x0f.general.LookupR\x06skills\"a\n" +
	"\x14CreateCatalogRequest\x121\n" +
	"\x05input\x18\x01 \x01(\v2\x1b.webitel.cases.InputCatalogR\x05input\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"\xac\x01\n" +
	"\x14UpdateCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x121\n" +
	"\x05input\x18\x02 \x01(\v2\x1b.webitel.cases.InputCatalogR\x05input\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x129\n" +
	"\vx_json_mask\x18\x04 \x03(\tB\x19\x92A\a@\x01\x8a\x01\x02^$\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEWR\txJsonMask\"&\n" +
	"\x14DeleteCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x03R\x02id\"\x81\x02\n" +
	"\x12ListCatalogRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x0e\n" +
	"\x02id\x18\x05 \x03(\x03R\x02id\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x12\x14\n" +
	"\x05state\x18\a \x01(\bR\x05state\x12\x14\n" +
	"\x05depth\x18\b \x01(\x03R\x05depth\x12\x1d\n" +
	"\n" +
	"sub_fields\x18\t \x03(\tR\tsubFields\x12&\n" +
	"\x0ehasSubservices\x18\n" +
	" \x01(\bR\x0ehasSubservices\"]\n" +
	"\x14LocateCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12\x1d\n" +
	"\n" +
	"sub_fields\x18\x03 \x03(\tR\tsubFields\"I\n" +
	"\x15LocateCatalogResponse\x120\n" +
	"\acatalog\x18\x01 \x01(\v2\x16.webitel.cases.CatalogR\acatalog2\xa2\x06\n" +
	"\bCatalogs\x12\x9d\x01\n" +
	"\fListCatalogs\x12!.webitel.cases.ListCatalogRequest\x1a\x1a.webitel.cases.CatalogList\"N\x92A0\x12.Retrieve a list of catalogs or search catalogs\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x11\x12\x0f/cases/catalogs\x12\x89\x01\n" +
	"\rCreateCatalog\x12#.webitel.cases.CreateCatalogRequest\x1a\x16.webitel.cases.Catalog\";\x92A\x16\x12\x14Create a new catalog\x90\xb5\x18\x00\x82\xd3\xe4\x93\x02\x18:\x05input\"\x0f/cases/catalogs\x12\xb3\x01\n" +
	"\rUpdateCatalog\x12#.webitel.cases.UpdateCatalogRequest\x1a\x16.webitel.cases.Catalog\"e\x92A\x1c\x12\x1aUpdate an existing catalog\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02<:\x05inputZ\x1d:\x05input2\x14/cases/catalogs/{id}\x1a\x14/cases/catalogs/{id}\x12\x87\x01\n" +
	"\rDeleteCatalog\x12#.webitel.cases.DeleteCatalogRequest\x1a\x1a.webitel.cases.CatalogList\"5\x92A\x12\x12\x10Delete a catalog\x90\xb5\x18\x03\x82\xd3\xe4\x93\x02\x16*\x14/cases/catalogs/{id}\x12\x97\x01\n" +
	"\rLocateCatalog\x12#.webitel.cases.LocateCatalogRequest\x1a$.webitel.cases.LocateCatalogResponse\";\x92A\x18\x12\x16Locate a catalog by ID\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x16\x12\x14/cases/catalogs/{id}\x1a\x10\x8a\xb5\x18\fdictionariesB\xa0\x01\n" +
	"\x11com.webitel.casesB\fCatalogProtoP\x01Z(github.com/webitel/cases/api/cases;cases\xa2\x02\x03WCX\xaa\x02\rWebitel.Cases\xca\x02\rWebitel\\Cases\xe2\x02\x19Webitel\\Cases\\GPBMetadata\xea\x02\x0eWebitel::Casesb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_catalog_proto_goTypes = []any{
	(*Catalog)(nil),               // 0: webitel.cases.Catalog
	(*CatalogList)(nil),           // 1: webitel.cases.CatalogList
	(*InputCatalog)(nil),          // 2: webitel.cases.InputCatalog
	(*CreateCatalogRequest)(nil),  // 3: webitel.cases.CreateCatalogRequest
	(*UpdateCatalogRequest)(nil),  // 4: webitel.cases.UpdateCatalogRequest
	(*DeleteCatalogRequest)(nil),  // 5: webitel.cases.DeleteCatalogRequest
	(*ListCatalogRequest)(nil),    // 6: webitel.cases.ListCatalogRequest
	(*LocateCatalogRequest)(nil),  // 7: webitel.cases.LocateCatalogRequest
	(*LocateCatalogResponse)(nil), // 8: webitel.cases.LocateCatalogResponse
	(*Lookup)(nil),                // 9: general.Lookup
	(*Service)(nil),               // 10: webitel.cases.Service
}
var file_catalog_proto_depIdxs = []int32{
	9,  // 0: webitel.cases.Catalog.sla:type_name -> general.Lookup
	9,  // 1: webitel.cases.Catalog.status:type_name -> general.Lookup
	9,  // 2: webitel.cases.Catalog.close_reason_group:type_name -> general.Lookup
	9,  // 3: webitel.cases.Catalog.teams:type_name -> general.Lookup
	9,  // 4: webitel.cases.Catalog.skills:type_name -> general.Lookup
	9,  // 5: webitel.cases.Catalog.created_by:type_name -> general.Lookup
	9,  // 6: webitel.cases.Catalog.updated_by:type_name -> general.Lookup
	10, // 7: webitel.cases.Catalog.service:type_name -> webitel.cases.Service
	0,  // 8: webitel.cases.CatalogList.items:type_name -> webitel.cases.Catalog
	9,  // 9: webitel.cases.InputCatalog.sla:type_name -> general.Lookup
	9,  // 10: webitel.cases.InputCatalog.status:type_name -> general.Lookup
	9,  // 11: webitel.cases.InputCatalog.close_reason_group:type_name -> general.Lookup
	9,  // 12: webitel.cases.InputCatalog.teams:type_name -> general.Lookup
	9,  // 13: webitel.cases.InputCatalog.skills:type_name -> general.Lookup
	2,  // 14: webitel.cases.CreateCatalogRequest.input:type_name -> webitel.cases.InputCatalog
	2,  // 15: webitel.cases.UpdateCatalogRequest.input:type_name -> webitel.cases.InputCatalog
	0,  // 16: webitel.cases.LocateCatalogResponse.catalog:type_name -> webitel.cases.Catalog
	6,  // 17: webitel.cases.Catalogs.ListCatalogs:input_type -> webitel.cases.ListCatalogRequest
	3,  // 18: webitel.cases.Catalogs.CreateCatalog:input_type -> webitel.cases.CreateCatalogRequest
	4,  // 19: webitel.cases.Catalogs.UpdateCatalog:input_type -> webitel.cases.UpdateCatalogRequest
	5,  // 20: webitel.cases.Catalogs.DeleteCatalog:input_type -> webitel.cases.DeleteCatalogRequest
	7,  // 21: webitel.cases.Catalogs.LocateCatalog:input_type -> webitel.cases.LocateCatalogRequest
	1,  // 22: webitel.cases.Catalogs.ListCatalogs:output_type -> webitel.cases.CatalogList
	0,  // 23: webitel.cases.Catalogs.CreateCatalog:output_type -> webitel.cases.Catalog
	0,  // 24: webitel.cases.Catalogs.UpdateCatalog:output_type -> webitel.cases.Catalog
	1,  // 25: webitel.cases.Catalogs.DeleteCatalog:output_type -> webitel.cases.CatalogList
	8,  // 26: webitel.cases.Catalogs.LocateCatalog:output_type -> webitel.cases.LocateCatalogResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	file_general_proto_init()
	file_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
