// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: close_reason_group.proto

package cases

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CloseReasonGroup message represents a close reason group entity with metadata
type CloseReasonGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the close reason group
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the close reason group
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the close reason group
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// CreatedAt timestamp of the close reason group
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt timestamp of the close reason group
	UpdatedAt int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// CreatedBy user of the close reason group
	CreatedBy *Lookup `protobuf:"bytes,22,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// UpdatedBy user of the close reason group
	UpdatedBy     *Lookup `protobuf:"bytes,23,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseReasonGroup) Reset() {
	*x = CloseReasonGroup{}
	mi := &file_close_reason_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseReasonGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseReasonGroup) ProtoMessage() {}

func (x *CloseReasonGroup) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseReasonGroup.ProtoReflect.Descriptor instead.
func (*CloseReasonGroup) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{0}
}

func (x *CloseReasonGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CloseReasonGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloseReasonGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CloseReasonGroup) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CloseReasonGroup) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CloseReasonGroup) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *CloseReasonGroup) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

// CloseReasonGroupList message contains a list of CloseReasonGroup items with pagination
type CloseReasonGroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Next          bool                   `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*CloseReasonGroup    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseReasonGroupList) Reset() {
	*x = CloseReasonGroupList{}
	mi := &file_close_reason_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseReasonGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseReasonGroupList) ProtoMessage() {}

func (x *CloseReasonGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseReasonGroupList.ProtoReflect.Descriptor instead.
func (*CloseReasonGroupList) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{1}
}

func (x *CloseReasonGroupList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CloseReasonGroupList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *CloseReasonGroupList) GetItems() []*CloseReasonGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

// CreateCloseReasonGroupRequest message for creating a new close reason group
type CreateCloseReasonGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Input *InputCloseReasonGroup `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// Fields to be retrieved as a result.
	Fields        []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCloseReasonGroupRequest) Reset() {
	*x = CreateCloseReasonGroupRequest{}
	mi := &file_close_reason_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCloseReasonGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCloseReasonGroupRequest) ProtoMessage() {}

func (x *CreateCloseReasonGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCloseReasonGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateCloseReasonGroupRequest) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCloseReasonGroupRequest) GetInput() *InputCloseReasonGroup {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateCloseReasonGroupRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type InputCloseReasonGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputCloseReasonGroup) Reset() {
	*x = InputCloseReasonGroup{}
	mi := &file_close_reason_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputCloseReasonGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputCloseReasonGroup) ProtoMessage() {}

func (x *InputCloseReasonGroup) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputCloseReasonGroup.ProtoReflect.Descriptor instead.
func (*InputCloseReasonGroup) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{3}
}

func (x *InputCloseReasonGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputCloseReasonGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// UpdateCloseReasonGroupRequest message for updating an existing close reason group
type UpdateCloseReasonGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Fields to be retrieved as a result.
	Fields []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Input  *InputCloseReasonGroup `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// ---- JSON PATCH fields mask ----
	// List of JPath fields specified in body(input).
	XJsonMask     []string `protobuf:"bytes,4,rep,name=x_json_mask,json=xJsonMask,proto3" json:"x_json_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCloseReasonGroupRequest) Reset() {
	*x = UpdateCloseReasonGroupRequest{}
	mi := &file_close_reason_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCloseReasonGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCloseReasonGroupRequest) ProtoMessage() {}

func (x *UpdateCloseReasonGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCloseReasonGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateCloseReasonGroupRequest) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCloseReasonGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCloseReasonGroupRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateCloseReasonGroupRequest) GetInput() *InputCloseReasonGroup {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *UpdateCloseReasonGroupRequest) GetXJsonMask() []string {
	if x != nil {
		return x.XJsonMask
	}
	return nil
}

// DeleteCloseReasonGroupRequest message for deleting an existing close reason group
type DeleteCloseReasonGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCloseReasonGroupRequest) Reset() {
	*x = DeleteCloseReasonGroupRequest{}
	mi := &file_close_reason_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCloseReasonGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCloseReasonGroupRequest) ProtoMessage() {}

func (x *DeleteCloseReasonGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCloseReasonGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteCloseReasonGroupRequest) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCloseReasonGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListCloseReasonGroupsRequest message for listing or searching close reason groups
type ListCloseReasonGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Id            []int64                `protobuf:"varint,5,rep,packed,name=id,proto3" json:"id,omitempty"`
	Q             string                 `protobuf:"bytes,6,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCloseReasonGroupsRequest) Reset() {
	*x = ListCloseReasonGroupsRequest{}
	mi := &file_close_reason_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCloseReasonGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCloseReasonGroupsRequest) ProtoMessage() {}

func (x *ListCloseReasonGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCloseReasonGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListCloseReasonGroupsRequest) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{6}
}

func (x *ListCloseReasonGroupsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCloseReasonGroupsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListCloseReasonGroupsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ListCloseReasonGroupsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListCloseReasonGroupsRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListCloseReasonGroupsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

// LocateCloseReasonGroupRequest message for locating a specific close reason group by ID
type LocateCloseReasonGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateCloseReasonGroupRequest) Reset() {
	*x = LocateCloseReasonGroupRequest{}
	mi := &file_close_reason_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateCloseReasonGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateCloseReasonGroupRequest) ProtoMessage() {}

func (x *LocateCloseReasonGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateCloseReasonGroupRequest.ProtoReflect.Descriptor instead.
func (*LocateCloseReasonGroupRequest) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{7}
}

func (x *LocateCloseReasonGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LocateCloseReasonGroupRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// LocateCloseReasonGroupResponse message contains a single close reason group entity
type LocateCloseReasonGroupResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CloseReasonGroup *CloseReasonGroup      `protobuf:"bytes,1,opt,name=close_reason_group,json=closeReasonGroup,proto3" json:"close_reason_group,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LocateCloseReasonGroupResponse) Reset() {
	*x = LocateCloseReasonGroupResponse{}
	mi := &file_close_reason_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateCloseReasonGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateCloseReasonGroupResponse) ProtoMessage() {}

func (x *LocateCloseReasonGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_close_reason_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateCloseReasonGroupResponse.ProtoReflect.Descriptor instead.
func (*LocateCloseReasonGroupResponse) Descriptor() ([]byte, []int) {
	return file_close_reason_group_proto_rawDescGZIP(), []int{8}
}

func (x *LocateCloseReasonGroupResponse) GetCloseReasonGroup() *CloseReasonGroup {
	if x != nil {
		return x.CloseReasonGroup
	}
	return nil
}

var File_close_reason_group_proto protoreflect.FileDescriptor

const file_close_reason_group_proto_rawDesc = "" +
	"\n" +
	"\x18close_reason_group.proto\x12\rwebitel.cases\x1a\rgeneral.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xf6\x01\n" +
	"\x10CloseReasonGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x16 \x01(\v2\x0f.general.LookupR\tcreatedBy\x12.\n" +
	"\n" +
	"updated_by\x18\x17 \x01(\v2\x0f.general.LookupR\tupdatedBy\"u\n" +
	"\x14CloseReasonGroupList\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\x125\n" +
	"\x05items\x18\x03 \x03(\v2\x1f.webitel.cases.CloseReasonGroupR\x05items\"\x81\x01\n" +
	"\x1dCreateCloseReasonGroupRequest\x12:\n" +
	"\x05input\x18\x01 \x01(\v2$.webitel.cases.InputCloseReasonGroupR\x05input\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields:\f\x92A\t\n" +
	"\a\xd2\x01\x04name\"M\n" +
	"\x15InputCloseReasonGroup\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xca\x01\n" +
	"\x1dUpdateCloseReasonGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12:\n" +
	"\x05input\x18\x03 \x01(\v2$.webitel.cases.InputCloseReasonGroupR\x05input\x129\n" +
	"\vx_json_mask\x18\x04 \x03(\tB\x19\x92A\a@\x01\x8a\x01\x02^$\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEWR\txJsonMask:\n" +
	"\x92A\a\n" +
	"\x05\xd2\x01\x02id\";\n" +
	"\x1dDeleteCloseReasonGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id:\n" +
	"\x92A\a\n" +
	"\x05\xd2\x01\x02id\"\x90\x01\n" +
	"\x1cListCloseReasonGroupsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x0e\n" +
	"\x02id\x18\x05 \x03(\x03R\x02id\x12\f\n" +
	"\x01q\x18\x06 \x01(\tR\x01q\"G\n" +
	"\x1dLocateCloseReasonGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"o\n" +
	"\x1eLocateCloseReasonGroupResponse\x12M\n" +
	"\x12close_reason_group\x18\x01 \x01(\v2\x1f.webitel.cases.CloseReasonGroupR\x10closeReasonGroup2\xb4\b\n" +
	"\x11CloseReasonGroups\x12\xda\x01\n" +
	"\x15ListCloseReasonGroups\x12+.webitel.cases.ListCloseReasonGroupsRequest\x1a#.webitel.cases.CloseReasonGroupList\"o\x92AF\x12DRetrieve a list of close reason groups or search close reason groups\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1c\x12\x1a/cases/close_reason_groups\x12\xba\x01\n" +
	"\x16CreateCloseReasonGroup\x12,.webitel.cases.CreateCloseReasonGroupRequest\x1a\x1f.webitel.cases.CloseReasonGroup\"Q\x92A!\x12\x1fCreate a new close reason group\x90\xb5\x18\x00\x82\xd3\xe4\x93\x02#:\x05input\"\x1a/cases/close_reason_groups\x12\xf0\x01\n" +
	"\x16UpdateCloseReasonGroup\x12,.webitel.cases.UpdateCloseReasonGroupRequest\x1a\x1f.webitel.cases.CloseReasonGroup\"\x86\x01\x92A'\x12%Update an existing close reason group\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02R:\x05inputZ(:\x05input2\x1f/cases/close_reason_groups/{id}\x1a\x1f/cases/close_reason_groups/{id}\x12\xb4\x01\n" +
	"\x16DeleteCloseReasonGroup\x12,.webitel.cases.DeleteCloseReasonGroupRequest\x1a\x1f.webitel.cases.CloseReasonGroup\"K\x92A\x1d\x12\x1bDelete a close reason group\x90\xb5\x18\x03\x82\xd3\xe4\x93\x02!*\x1f/cases/close_reason_groups/{id}\x12\xc8\x01\n" +
	"\x16LocateCloseReasonGroup\x12,.webitel.cases.LocateCloseReasonGroupRequest\x1a-.webitel.cases.LocateCloseReasonGroupResponse\"Q\x92A#\x12!Locate a close reason group by ID\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02!\x12\x1f/cases/close_reason_groups/{id}\x1a\x10\x8a\xb5\x18\fdictionariesB\xa9\x01\n" +
	"\x11com.webitel.casesB\x15CloseReasonGroupProtoP\x01Z(github.com/webitel/cases/api/cases;cases\xa2\x02\x03WCX\xaa\x02\rWebitel.Cases\xca\x02\rWebitel\\Cases\xe2\x02\x19Webitel\\Cases\\GPBMetadata\xea\x02\x0eWebitel::Casesb\x06proto3"

var (
	file_close_reason_group_proto_rawDescOnce sync.Once
	file_close_reason_group_proto_rawDescData []byte
)

func file_close_reason_group_proto_rawDescGZIP() []byte {
	file_close_reason_group_proto_rawDescOnce.Do(func() {
		file_close_reason_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_close_reason_group_proto_rawDesc), len(file_close_reason_group_proto_rawDesc)))
	})
	return file_close_reason_group_proto_rawDescData
}

var file_close_reason_group_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_close_reason_group_proto_goTypes = []any{
	(*CloseReasonGroup)(nil),               // 0: webitel.cases.CloseReasonGroup
	(*CloseReasonGroupList)(nil),           // 1: webitel.cases.CloseReasonGroupList
	(*CreateCloseReasonGroupRequest)(nil),  // 2: webitel.cases.CreateCloseReasonGroupRequest
	(*InputCloseReasonGroup)(nil),          // 3: webitel.cases.InputCloseReasonGroup
	(*UpdateCloseReasonGroupRequest)(nil),  // 4: webitel.cases.UpdateCloseReasonGroupRequest
	(*DeleteCloseReasonGroupRequest)(nil),  // 5: webitel.cases.DeleteCloseReasonGroupRequest
	(*ListCloseReasonGroupsRequest)(nil),   // 6: webitel.cases.ListCloseReasonGroupsRequest
	(*LocateCloseReasonGroupRequest)(nil),  // 7: webitel.cases.LocateCloseReasonGroupRequest
	(*LocateCloseReasonGroupResponse)(nil), // 8: webitel.cases.LocateCloseReasonGroupResponse
	(*Lookup)(nil),                         // 9: general.Lookup
}
var file_close_reason_group_proto_depIdxs = []int32{
	9,  // 0: webitel.cases.CloseReasonGroup.created_by:type_name -> general.Lookup
	9,  // 1: webitel.cases.CloseReasonGroup.updated_by:type_name -> general.Lookup
	0,  // 2: webitel.cases.CloseReasonGroupList.items:type_name -> webitel.cases.CloseReasonGroup
	3,  // 3: webitel.cases.CreateCloseReasonGroupRequest.input:type_name -> webitel.cases.InputCloseReasonGroup
	3,  // 4: webitel.cases.UpdateCloseReasonGroupRequest.input:type_name -> webitel.cases.InputCloseReasonGroup
	0,  // 5: webitel.cases.LocateCloseReasonGroupResponse.close_reason_group:type_name -> webitel.cases.CloseReasonGroup
	6,  // 6: webitel.cases.CloseReasonGroups.ListCloseReasonGroups:input_type -> webitel.cases.ListCloseReasonGroupsRequest
	2,  // 7: webitel.cases.CloseReasonGroups.CreateCloseReasonGroup:input_type -> webitel.cases.CreateCloseReasonGroupRequest
	4,  // 8: webitel.cases.CloseReasonGroups.UpdateCloseReasonGroup:input_type -> webitel.cases.UpdateCloseReasonGroupRequest
	5,  // 9: webitel.cases.CloseReasonGroups.DeleteCloseReasonGroup:input_type -> webitel.cases.DeleteCloseReasonGroupRequest
	7,  // 10: webitel.cases.CloseReasonGroups.LocateCloseReasonGroup:input_type -> webitel.cases.LocateCloseReasonGroupRequest
	1,  // 11: webitel.cases.CloseReasonGroups.ListCloseReasonGroups:output_type -> webitel.cases.CloseReasonGroupList
	0,  // 12: webitel.cases.CloseReasonGroups.CreateCloseReasonGroup:output_type -> webitel.cases.CloseReasonGroup
	0,  // 13: webitel.cases.CloseReasonGroups.UpdateCloseReasonGroup:output_type -> webitel.cases.CloseReasonGroup
	0,  // 14: webitel.cases.CloseReasonGroups.DeleteCloseReasonGroup:output_type -> webitel.cases.CloseReasonGroup
	8,  // 15: webitel.cases.CloseReasonGroups.LocateCloseReasonGroup:output_type -> webitel.cases.LocateCloseReasonGroupResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_close_reason_group_proto_init() }
func file_close_reason_group_proto_init() {
	if File_close_reason_group_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_close_reason_group_proto_rawDesc), len(file_close_reason_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_close_reason_group_proto_goTypes,
		DependencyIndexes: file_close_reason_group_proto_depIdxs,
		MessageInfos:      file_close_reason_group_proto_msgTypes,
	}.Build()
	File_close_reason_group_proto = out.File
	file_close_reason_group_proto_goTypes = nil
	file_close_reason_group_proto_depIdxs = nil
}
