// Code generated by protoc-gen-go-webitel. DO NOT EDIT.
// versions:
// - protoc-gen-go-webitel v1.0.0
// - protoc                (unknown)

package cases

// WebitelServicesInfo is the list of services defined in proto files.
type WebitelServicesInfo map[string]WebitelServices

type WebitelServices struct {
	ObjClass           string
	AdditionalLicenses []string
	WebitelMethods     map[string]WebitelMethod
}

// WebitelMethod is the list of methods defined in this service.
type WebitelMethod struct {
	HttpBindings []*HttpBinding
	Access       int
	Input        string
	Output       string
}

type HttpBinding struct {
	Path   string
	Method string
}

var WebitelAPI = WebitelServicesInfo{
	"Services": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListServices": WebitelMethod{
				Access: 0,
				Input:  "ListServiceRequest",
				Output: "ServiceList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/services",
						Method: "GET",
					},
				},
			},
			"CreateService": WebitelMethod{
				Access: 0,
				Input:  "CreateServiceRequest",
				Output: "Service",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/services",
						Method: "POST",
					},
				},
			},
			"UpdateService": WebitelMethod{
				Access: 0,
				Input:  "UpdateServiceRequest",
				Output: "Service",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/services/{id}",
						Method: "PUT",
					},
					{
						Path:   "/cases/services/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteService": WebitelMethod{
				Access: 0,
				Input:  "DeleteServiceRequest",
				Output: "ServiceList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/services/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateService": WebitelMethod{
				Access: 0,
				Input:  "LocateServiceRequest",
				Output: "LocateServiceResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/services/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"CaseComments": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"LocateComment": WebitelMethod{
				Access: 0,
				Input:  "LocateCommentRequest",
				Output: "CaseComment",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/comments/{etag}",
						Method: "GET",
					},
				},
			},
			"UpdateComment": WebitelMethod{
				Access: 0,
				Input:  "UpdateCommentRequest",
				Output: "CaseComment",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/comments/{input.etag}",
						Method: "PUT",
					},
					{
						Path:   "/cases/comments/{input.etag}",
						Method: "PATCH",
					},
				},
			},
			"DeleteComment": WebitelMethod{
				Access: 0,
				Input:  "DeleteCommentRequest",
				Output: "CaseComment",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/comments/{etag}",
						Method: "DELETE",
					},
				},
			},
			"ListComments": WebitelMethod{
				Access: 0,
				Input:  "ListCommentsRequest",
				Output: "CaseCommentList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/comments",
						Method: "GET",
					},
				},
			},
			"PublishComment": WebitelMethod{
				Access: 0,
				Input:  "PublishCommentRequest",
				Output: "CaseComment",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/comments",
						Method: "POST",
					},
				},
			},
		},
	},
	"CaseFiles": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListFiles": WebitelMethod{
				Access: 0,
				Input:  "ListFilesRequest",
				Output: "CaseFileList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/files",
						Method: "GET",
					},
				},
			},
		},
	},
	"CaseLinks": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"LocateLink": WebitelMethod{
				Access: 0,
				Input:  "LocateLinkRequest",
				Output: "CaseLink",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/links/{etag}",
						Method: "GET",
					},
				},
			},
			"UpdateLink": WebitelMethod{
				Access: 0,
				Input:  "UpdateLinkRequest",
				Output: "CaseLink",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/links/{input.etag}",
						Method: "PUT",
					},
					{
						Path:   "/cases/links/{input.etag}",
						Method: "PATCH",
					},
				},
			},
			"DeleteLink": WebitelMethod{
				Access: 0,
				Input:  "DeleteLinkRequest",
				Output: "CaseLink",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/links/{etag}",
						Method: "DELETE",
					},
				},
			},
			"ListLinks": WebitelMethod{
				Access: 0,
				Input:  "ListLinksRequest",
				Output: "CaseLinkList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/links",
						Method: "GET",
					},
				},
			},
			"MergeLinks": WebitelMethod{
				Access: 0,
				Input:  "MergeLinksRequest",
				Output: "CaseLinkList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/links",
						Method: "POST",
					},
				},
			},
		},
	},
	"SLAs": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListSLAs": WebitelMethod{
				Access: 0,
				Input:  "ListSLARequest",
				Output: "SLAList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/slas",
						Method: "GET",
					},
				},
			},
			"CreateSLA": WebitelMethod{
				Access: 0,
				Input:  "CreateSLARequest",
				Output: "SLA",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/slas",
						Method: "POST",
					},
				},
			},
			"UpdateSLA": WebitelMethod{
				Access: 0,
				Input:  "UpdateSLARequest",
				Output: "SLA",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/slas/{id}",
						Method: "PUT",
					},
					{
						Path:   "/cases/slas/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteSLA": WebitelMethod{
				Access: 0,
				Input:  "DeleteSLARequest",
				Output: "SLA",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/slas/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateSLA": WebitelMethod{
				Access: 0,
				Input:  "LocateSLARequest",
				Output: "LocateSLAResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/slas/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"SLAConditions": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListSLAConditions": WebitelMethod{
				Access: 0,
				Input:  "ListSLAConditionRequest",
				Output: "SLAConditionList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/slas/{sla_id}/sla_conditions",
						Method: "GET",
					},
				},
			},
			"CreateSLACondition": WebitelMethod{
				Access: 0,
				Input:  "CreateSLAConditionRequest",
				Output: "SLACondition",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/slas/{sla_id}/sla_condition",
						Method: "POST",
					},
				},
			},
			"UpdateSLACondition": WebitelMethod{
				Access: 0,
				Input:  "UpdateSLAConditionRequest",
				Output: "SLACondition",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/slas/{sla_id}/sla_condition/{id}",
						Method: "PUT",
					},
					{
						Path:   "/slas/{sla_id}/sla_condition/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteSLACondition": WebitelMethod{
				Access: 0,
				Input:  "DeleteSLAConditionRequest",
				Output: "SLACondition",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/slas/{sla_id}/sla_condition/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateSLACondition": WebitelMethod{
				Access: 0,
				Input:  "LocateSLAConditionRequest",
				Output: "LocateSLAConditionResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/slas/{sla_id}/sla_condition/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"Cases": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"SearchCases": WebitelMethod{
				Access: 0,
				Input:  "SearchCasesRequest",
				Output: "CaseList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases",
						Method: "GET",
					},
				},
			},
			"LocateCase": WebitelMethod{
				Access: 0,
				Input:  "LocateCaseRequest",
				Output: "Case",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{etag}",
						Method: "GET",
					},
				},
			},
			"CreateCase": WebitelMethod{
				Access: 0,
				Input:  "CreateCaseRequest",
				Output: "Case",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases",
						Method: "POST",
					},
				},
			},
			"UpdateCase": WebitelMethod{
				Access: 0,
				Input:  "UpdateCaseRequest",
				Output: "Case",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{input.etag}",
						Method: "PUT",
					},
					{
						Path:   "/cases/{input.etag}",
						Method: "PATCH",
					},
				},
			},
			"DeleteCase": WebitelMethod{
				Access: 0,
				Input:  "DeleteCaseRequest",
				Output: "Case",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{etag}",
						Method: "DELETE",
					},
				},
			},
		},
	},
	"RelatedCases": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"LocateRelatedCase": WebitelMethod{
				Access: 0,
				Input:  "LocateRelatedCaseRequest",
				Output: "RelatedCase",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/related/{etag}",
						Method: "GET",
					},
				},
			},
			"UpdateRelatedCase": WebitelMethod{
				Access: 0,
				Input:  "UpdateRelatedCaseRequest",
				Output: "RelatedCase",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/related/{input.etag}",
						Method: "PUT",
					},
					{
						Path:   "/cases/related/{input.etag}",
						Method: "PATCH",
					},
				},
			},
			"DeleteRelatedCase": WebitelMethod{
				Access: 0,
				Input:  "DeleteRelatedCaseRequest",
				Output: "RelatedCase",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/related/{etag}",
						Method: "DELETE",
					},
				},
			},
			"ListRelatedCases": WebitelMethod{
				Access: 0,
				Input:  "ListRelatedCasesRequest",
				Output: "RelatedCaseList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/related",
						Method: "GET",
					},
				},
			},
			"MergeRelatedCases": WebitelMethod{
				Access: 0,
				Input:  "MergeRelatedCasesRequest",
				Output: "RelatedCaseList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/related",
						Method: "POST",
					},
				},
			},
			"ResetRelatedCases": WebitelMethod{
				Access: 0,
				Input:  "ResetRelatedCasesRequest",
				Output: "RelatedCaseList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/{case_etag}/related",
						Method: "PUT",
					},
				},
			},
		},
	},
	"Catalogs": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListCatalogs": WebitelMethod{
				Access: 0,
				Input:  "ListCatalogRequest",
				Output: "CatalogList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/catalogs",
						Method: "GET",
					},
				},
			},
			"CreateCatalog": WebitelMethod{
				Access: 0,
				Input:  "CreateCatalogRequest",
				Output: "Catalog",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/catalogs",
						Method: "POST",
					},
				},
			},
			"UpdateCatalog": WebitelMethod{
				Access: 0,
				Input:  "UpdateCatalogRequest",
				Output: "Catalog",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/catalogs/{id}",
						Method: "PUT",
					},
					{
						Path:   "/cases/catalogs/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteCatalog": WebitelMethod{
				Access: 0,
				Input:  "DeleteCatalogRequest",
				Output: "CatalogList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/catalogs/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateCatalog": WebitelMethod{
				Access: 0,
				Input:  "LocateCatalogRequest",
				Output: "LocateCatalogResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/catalogs/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"CloseReasons": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListCloseReasons": WebitelMethod{
				Access: 0,
				Input:  "ListCloseReasonRequest",
				Output: "CloseReasonList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/close_reason_groups/{close_reason_group_id}/close_reasons",
						Method: "GET",
					},
				},
			},
			"CreateCloseReason": WebitelMethod{
				Access: 0,
				Input:  "CreateCloseReasonRequest",
				Output: "CloseReason",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/close_reason_groups/{close_reason_group_id}/close_reasons",
						Method: "POST",
					},
				},
			},
			"UpdateCloseReason": WebitelMethod{
				Access: 0,
				Input:  "UpdateCloseReasonRequest",
				Output: "CloseReason",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/close_reason_groups/{close_reason_group_id}/close_reasons/{id}",
						Method: "PUT",
					},
					{
						Path:   "/close_reason_groups/{close_reason_group_id}/close_reasons/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteCloseReason": WebitelMethod{
				Access: 0,
				Input:  "DeleteCloseReasonRequest",
				Output: "CloseReason",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/close_reason_groups/{close_reason_group_id}/close_reasons/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateCloseReason": WebitelMethod{
				Access: 0,
				Input:  "LocateCloseReasonRequest",
				Output: "LocateCloseReasonResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/close_reason_groups/{close_reason_group_id}/close_reasons/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"CloseReasonGroups": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListCloseReasonGroups": WebitelMethod{
				Access: 0,
				Input:  "ListCloseReasonGroupsRequest",
				Output: "CloseReasonGroupList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/close_reason_groups",
						Method: "GET",
					},
				},
			},
			"CreateCloseReasonGroup": WebitelMethod{
				Access: 0,
				Input:  "CreateCloseReasonGroupRequest",
				Output: "CloseReasonGroup",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/close_reason_groups",
						Method: "POST",
					},
				},
			},
			"UpdateCloseReasonGroup": WebitelMethod{
				Access: 0,
				Input:  "UpdateCloseReasonGroupRequest",
				Output: "CloseReasonGroup",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/close_reason_groups/{id}",
						Method: "PUT",
					},
					{
						Path:   "/cases/close_reason_groups/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteCloseReasonGroup": WebitelMethod{
				Access: 0,
				Input:  "DeleteCloseReasonGroupRequest",
				Output: "CloseReasonGroup",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/close_reason_groups/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateCloseReasonGroup": WebitelMethod{
				Access: 0,
				Input:  "LocateCloseReasonGroupRequest",
				Output: "LocateCloseReasonGroupResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/close_reason_groups/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"Priorities": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListPriorities": WebitelMethod{
				Access: 0,
				Input:  "ListPriorityRequest",
				Output: "PriorityList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/priorities",
						Method: "GET",
					},
				},
			},
			"CreatePriority": WebitelMethod{
				Access: 0,
				Input:  "CreatePriorityRequest",
				Output: "Priority",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/priorities",
						Method: "POST",
					},
				},
			},
			"UpdatePriority": WebitelMethod{
				Access: 0,
				Input:  "UpdatePriorityRequest",
				Output: "Priority",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/priorities/{id}",
						Method: "PUT",
					},
					{
						Path:   "/cases/priorities/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeletePriority": WebitelMethod{
				Access: 0,
				Input:  "DeletePriorityRequest",
				Output: "Priority",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/priorities/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocatePriority": WebitelMethod{
				Access: 0,
				Input:  "LocatePriorityRequest",
				Output: "LocatePriorityResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/priorities/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"Sources": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListSources": WebitelMethod{
				Access: 0,
				Input:  "ListSourceRequest",
				Output: "SourceList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/sources",
						Method: "GET",
					},
				},
			},
			"CreateSource": WebitelMethod{
				Access: 0,
				Input:  "CreateSourceRequest",
				Output: "Source",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/sources",
						Method: "POST",
					},
				},
			},
			"UpdateSource": WebitelMethod{
				Access: 0,
				Input:  "UpdateSourceRequest",
				Output: "Source",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/sources/{id}",
						Method: "PUT",
					},
					{
						Path:   "/cases/sources/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteSource": WebitelMethod{
				Access: 0,
				Input:  "DeleteSourceRequest",
				Output: "Source",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/sources/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateSource": WebitelMethod{
				Access: 0,
				Input:  "LocateSourceRequest",
				Output: "LocateSourceResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/sources/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"Statuses": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListStatuses": WebitelMethod{
				Access: 0,
				Input:  "ListStatusRequest",
				Output: "StatusList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/statuses",
						Method: "GET",
					},
				},
			},
			"CreateStatus": WebitelMethod{
				Access: 0,
				Input:  "CreateStatusRequest",
				Output: "Status",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/statuses",
						Method: "POST",
					},
				},
			},
			"UpdateStatus": WebitelMethod{
				Access: 0,
				Input:  "UpdateStatusRequest",
				Output: "Status",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/statuses/{id}",
						Method: "PUT",
					},
					{
						Path:   "/cases/statuses/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteStatus": WebitelMethod{
				Access: 0,
				Input:  "DeleteStatusRequest",
				Output: "Status",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/statuses/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateStatus": WebitelMethod{
				Access: 0,
				Input:  "LocateStatusRequest",
				Output: "LocateStatusResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/cases/statuses/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
	"StatusConditions": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListStatusConditions": WebitelMethod{
				Access: 0,
				Input:  "ListStatusConditionRequest",
				Output: "StatusConditionList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/statuses/{status_id}/status",
						Method: "GET",
					},
				},
			},
			"CreateStatusCondition": WebitelMethod{
				Access: 0,
				Input:  "CreateStatusConditionRequest",
				Output: "StatusCondition",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/statuses/{status_id}/status",
						Method: "POST",
					},
				},
			},
			"UpdateStatusCondition": WebitelMethod{
				Access: 0,
				Input:  "UpdateStatusConditionRequest",
				Output: "StatusCondition",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/statuses/{status_id}/status/{id}",
						Method: "PUT",
					},
					{
						Path:   "/statuses/{status_id}/status/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteStatusCondition": WebitelMethod{
				Access: 0,
				Input:  "DeleteStatusConditionRequest",
				Output: "StatusCondition",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/statuses/{status_id}/status/{id}",
						Method: "DELETE",
					},
				},
			},
			"LocateStatusCondition": WebitelMethod{
				Access: 0,
				Input:  "LocateStatusConditionRequest",
				Output: "LocateStatusConditionResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/statuses/{status_id}/status/{id}",
						Method: "GET",
					},
				},
			},
		},
	},
}
