// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: status_condition.proto

package cases

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusCondition message represents a status entity with metadata
type StatusCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the status condition
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the status condition
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the status condition
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Initial status condition
	Initial bool `protobuf:"varint,4,opt,name=initial,proto3" json:"initial,omitempty"`
	// Final status condition
	Final bool `protobuf:"varint,5,opt,name=final,proto3" json:"final,omitempty"`
	// Status ID of the status condition
	StatusId int64 `protobuf:"varint,6,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	// CreatedAt timestamp of the status condition
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt timestamp of the status condition
	UpdatedAt int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// CreatedBy user of the status condition
	CreatedBy *Lookup `protobuf:"bytes,22,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// UpdatedBy user of the status condition
	UpdatedBy     *Lookup `protobuf:"bytes,23,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCondition) Reset() {
	*x = StatusCondition{}
	mi := &file_status_condition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCondition) ProtoMessage() {}

func (x *StatusCondition) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCondition.ProtoReflect.Descriptor instead.
func (*StatusCondition) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{0}
}

func (x *StatusCondition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusCondition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StatusCondition) GetInitial() bool {
	if x != nil {
		return x.Initial
	}
	return false
}

func (x *StatusCondition) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *StatusCondition) GetStatusId() int64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *StatusCondition) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StatusCondition) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *StatusCondition) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *StatusCondition) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

// InputStatusCondition message for inputting status condition data
type InputStatusCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the status condition
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the status condition
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Initial status condition
	Initial *wrapperspb.BoolValue `protobuf:"bytes,4,opt,name=initial,proto3" json:"initial,omitempty"`
	// Final status condition
	Final         *wrapperspb.BoolValue `protobuf:"bytes,5,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputStatusCondition) Reset() {
	*x = InputStatusCondition{}
	mi := &file_status_condition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputStatusCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputStatusCondition) ProtoMessage() {}

func (x *InputStatusCondition) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputStatusCondition.ProtoReflect.Descriptor instead.
func (*InputStatusCondition) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{1}
}

func (x *InputStatusCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputStatusCondition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InputStatusCondition) GetInitial() *wrapperspb.BoolValue {
	if x != nil {
		return x.Initial
	}
	return nil
}

func (x *InputStatusCondition) GetFinal() *wrapperspb.BoolValue {
	if x != nil {
		return x.Final
	}
	return nil
}

// StatusConditionList message contains a list of StatusCondition items with pagination
type StatusConditionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Next          bool                   `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*StatusCondition     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusConditionList) Reset() {
	*x = StatusConditionList{}
	mi := &file_status_condition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusConditionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusConditionList) ProtoMessage() {}

func (x *StatusConditionList) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusConditionList.ProtoReflect.Descriptor instead.
func (*StatusConditionList) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{2}
}

func (x *StatusConditionList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *StatusConditionList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *StatusConditionList) GetItems() []*StatusCondition {
	if x != nil {
		return x.Items
	}
	return nil
}

type InputCreateStatusCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputCreateStatusCondition) Reset() {
	*x = InputCreateStatusCondition{}
	mi := &file_status_condition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputCreateStatusCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputCreateStatusCondition) ProtoMessage() {}

func (x *InputCreateStatusCondition) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputCreateStatusCondition.ProtoReflect.Descriptor instead.
func (*InputCreateStatusCondition) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{3}
}

func (x *InputCreateStatusCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputCreateStatusCondition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreateStatusConditionRequest message for creating a new status
type CreateStatusConditionRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Input         *InputCreateStatusCondition `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	StatusId      int64                       `protobuf:"varint,2,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	Fields        []string                    `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStatusConditionRequest) Reset() {
	*x = CreateStatusConditionRequest{}
	mi := &file_status_condition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStatusConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatusConditionRequest) ProtoMessage() {}

func (x *CreateStatusConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatusConditionRequest.ProtoReflect.Descriptor instead.
func (*CreateStatusConditionRequest) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStatusConditionRequest) GetInput() *InputCreateStatusCondition {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateStatusConditionRequest) GetStatusId() int64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *CreateStatusConditionRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// UpdateStatusConditionRequest message for updating an existing status
type UpdateStatusConditionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StatusId int64                  `protobuf:"varint,1,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	Id       int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Input    *InputStatusCondition  `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Fields   []string               `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	// ---- JSON PATCH fields mask ----
	// List of JPath fields specified in body(input).
	XJsonMask     []string `protobuf:"bytes,5,rep,name=x_json_mask,json=xJsonMask,proto3" json:"x_json_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusConditionRequest) Reset() {
	*x = UpdateStatusConditionRequest{}
	mi := &file_status_condition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusConditionRequest) ProtoMessage() {}

func (x *UpdateStatusConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusConditionRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusConditionRequest) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusConditionRequest) GetStatusId() int64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *UpdateStatusConditionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusConditionRequest) GetInput() *InputStatusCondition {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *UpdateStatusConditionRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateStatusConditionRequest) GetXJsonMask() []string {
	if x != nil {
		return x.XJsonMask
	}
	return nil
}

// DeleteStatusConditionRequest message for deleting an existing status
type DeleteStatusConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusId      int64                  `protobuf:"varint,2,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStatusConditionRequest) Reset() {
	*x = DeleteStatusConditionRequest{}
	mi := &file_status_condition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStatusConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStatusConditionRequest) ProtoMessage() {}

func (x *DeleteStatusConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStatusConditionRequest.ProtoReflect.Descriptor instead.
func (*DeleteStatusConditionRequest) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStatusConditionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteStatusConditionRequest) GetStatusId() int64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

// ListStatusConditionRequest message for listing or searching statuses
type ListStatusConditionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page number of result dataset records. offset = (page*size)
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Size count of records on result page. limit = (size++)
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Fields to be retrieved as a result.
	Fields []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Sort the result according to fields.
	Sort string `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	// Filter by unique IDs.
	Id []int64 `protobuf:"varint,5,rep,packed,name=id,proto3" json:"id,omitempty"`
	// Search query string for filtering by name. Supports:
	// - Wildcards (*) for substring matching
	// - Placeholder (?) for single character substitution
	// - Exact match for full names
	Q string `protobuf:"bytes,6,opt,name=q,proto3" json:"q,omitempty"`
	// Filter by Status Id.
	StatusId      int64 `protobuf:"varint,7,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatusConditionRequest) Reset() {
	*x = ListStatusConditionRequest{}
	mi := &file_status_condition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatusConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatusConditionRequest) ProtoMessage() {}

func (x *ListStatusConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatusConditionRequest.ProtoReflect.Descriptor instead.
func (*ListStatusConditionRequest) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{7}
}

func (x *ListStatusConditionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStatusConditionRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListStatusConditionRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ListStatusConditionRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListStatusConditionRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListStatusConditionRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListStatusConditionRequest) GetStatusId() int64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

// LocateStatusConditionRequest message for locating a specific status by ID
type LocateStatusConditionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the status condition to be located
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the status to be located
	StatusId int64 `protobuf:"varint,2,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	// Fields to be retrieved as a result.
	Fields        []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateStatusConditionRequest) Reset() {
	*x = LocateStatusConditionRequest{}
	mi := &file_status_condition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateStatusConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateStatusConditionRequest) ProtoMessage() {}

func (x *LocateStatusConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateStatusConditionRequest.ProtoReflect.Descriptor instead.
func (*LocateStatusConditionRequest) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{8}
}

func (x *LocateStatusConditionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LocateStatusConditionRequest) GetStatusId() int64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *LocateStatusConditionRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// LocateStatusConditionResponse message contains a single status entity
type LocateStatusConditionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusCondition       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateStatusConditionResponse) Reset() {
	*x = LocateStatusConditionResponse{}
	mi := &file_status_condition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateStatusConditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateStatusConditionResponse) ProtoMessage() {}

func (x *LocateStatusConditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_condition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateStatusConditionResponse.ProtoReflect.Descriptor instead.
func (*LocateStatusConditionResponse) Descriptor() ([]byte, []int) {
	return file_status_condition_proto_rawDescGZIP(), []int{9}
}

func (x *LocateStatusConditionResponse) GetStatus() *StatusCondition {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_status_condition_proto protoreflect.FileDescriptor

const file_status_condition_proto_rawDesc = "" +
	"\n" +
	"\x16status_condition.proto\x12\rwebitel.cases\x1a\rgeneral.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xc2\x02\n" +
	"\x0fStatusCondition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\ainitial\x18\x04 \x01(\bR\ainitial\x12\x14\n" +
	"\x05final\x18\x05 \x01(\bR\x05final\x12\x1b\n" +
	"\tstatus_id\x18\x06 \x01(\x03R\bstatusId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x16 \x01(\v2\x0f.general.LookupR\tcreatedBy\x12.\n" +
	"\n" +
	"updated_by\x18\x17 \x01(\v2\x0f.general.LookupR\tupdatedBy\"\xb4\x01\n" +
	"\x14InputStatusCondition\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\ainitial\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\ainitial\x120\n" +
	"\x05final\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\x05final\"s\n" +
	"\x13StatusConditionList\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\x124\n" +
	"\x05items\x18\x03 \x03(\v2\x1e.webitel.cases.StatusConditionR\x05items\"R\n" +
	"\x1aInputCreateStatusCondition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x94\x01\n" +
	"\x1cCreateStatusConditionRequest\x12?\n" +
	"\x05input\x18\x01 \x01(\v2).webitel.cases.InputCreateStatusConditionR\x05input\x12\x1b\n" +
	"\tstatus_id\x18\x02 \x01(\x03R\bstatusId\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"\xe5\x01\n" +
	"\x1cUpdateStatusConditionRequest\x12\x1b\n" +
	"\tstatus_id\x18\x01 \x01(\x03R\bstatusId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x129\n" +
	"\x05input\x18\x03 \x01(\v2#.webitel.cases.InputStatusConditionR\x05input\x12\x16\n" +
	"\x06fields\x18\x04 \x03(\tR\x06fields\x129\n" +
	"\vx_json_mask\x18\x05 \x03(\tB\x19\x92A\a@\x01\x8a\x01\x02^$\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEWR\txJsonMask:\n" +
	"\x92A\a\n" +
	"\x05\xd2\x01\x02id\"^\n" +
	"\x1cDeleteStatusConditionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tstatus_id\x18\x02 \x01(\x03R\bstatusId:\x11\x92A\x0e\n" +
	"\f\xd2\x01\tstatus_id\"\xab\x01\n" +
	"\x1aListStatusConditionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x0e\n" +
	"\x02id\x18\x05 \x03(\x03R\x02id\x12\f\n" +
	"\x01q\x18\x06 \x01(\tR\x01q\x12\x1b\n" +
	"\tstatus_id\x18\a \x01(\x03R\bstatusId\"c\n" +
	"\x1cLocateStatusConditionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tstatus_id\x18\x02 \x01(\x03R\bstatusId\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"W\n" +
	"\x1dLocateStatusConditionResponse\x126\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.webitel.cases.StatusConditionR\x06status2\x9a\b\n" +
	"\x10StatusConditions\x12\xcb\x01\n" +
	"\x14ListStatusConditions\x12).webitel.cases.ListStatusConditionRequest\x1a\".webitel.cases.StatusConditionList\"d\x92A9\x127Retrieve a list of statuses or search status conditions\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1e\x12\x1c/statuses/{status_id}/status\x12\xb7\x01\n" +
	"\x15CreateStatusCondition\x12+.webitel.cases.CreateStatusConditionRequest\x1a\x1e.webitel.cases.StatusCondition\"Q\x92A\x1f\x12\x1dCreate a new status condition\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02%:\x05input\"\x1c/statuses/{status_id}/status\x12\xef\x01\n" +
	"\x15UpdateStatusCondition\x12+.webitel.cases.UpdateStatusConditionRequest\x1a\x1e.webitel.cases.StatusCondition\"\x88\x01\x92A%\x12#Update an existing status condition\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02V:\x05inputZ*:\x05input2!/statuses/{status_id}/status/{id}\x1a!/statuses/{status_id}/status/{id}\x12\xb1\x01\n" +
	"\x15DeleteStatusCondition\x12+.webitel.cases.DeleteStatusConditionRequest\x1a\x1e.webitel.cases.StatusCondition\"K\x92A\x1b\x12\x19Delete a status condition\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02#*!/statuses/{status_id}/status/{id}\x12\xc5\x01\n" +
	"\x15LocateStatusCondition\x12+.webitel.cases.LocateStatusConditionRequest\x1a,.webitel.cases.LocateStatusConditionResponse\"Q\x92A!\x12\x1fLocate a status condition by ID\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02#\x12!/statuses/{status_id}/status/{id}\x1a\x10\x8a\xb5\x18\fcase_lookupsB\xa8\x01\n" +
	"\x11com.webitel.casesB\x14StatusConditionProtoP\x01Z(github.com/webitel/cases/api/cases;cases\xa2\x02\x03WCX\xaa\x02\rWebitel.Cases\xca\x02\rWebitel\\Cases\xe2\x02\x19Webitel\\Cases\\GPBMetadata\xea\x02\x0eWebitel::Casesb\x06proto3"

var (
	file_status_condition_proto_rawDescOnce sync.Once
	file_status_condition_proto_rawDescData []byte
)

func file_status_condition_proto_rawDescGZIP() []byte {
	file_status_condition_proto_rawDescOnce.Do(func() {
		file_status_condition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_condition_proto_rawDesc), len(file_status_condition_proto_rawDesc)))
	})
	return file_status_condition_proto_rawDescData
}

var file_status_condition_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_status_condition_proto_goTypes = []any{
	(*StatusCondition)(nil),               // 0: webitel.cases.StatusCondition
	(*InputStatusCondition)(nil),          // 1: webitel.cases.InputStatusCondition
	(*StatusConditionList)(nil),           // 2: webitel.cases.StatusConditionList
	(*InputCreateStatusCondition)(nil),    // 3: webitel.cases.InputCreateStatusCondition
	(*CreateStatusConditionRequest)(nil),  // 4: webitel.cases.CreateStatusConditionRequest
	(*UpdateStatusConditionRequest)(nil),  // 5: webitel.cases.UpdateStatusConditionRequest
	(*DeleteStatusConditionRequest)(nil),  // 6: webitel.cases.DeleteStatusConditionRequest
	(*ListStatusConditionRequest)(nil),    // 7: webitel.cases.ListStatusConditionRequest
	(*LocateStatusConditionRequest)(nil),  // 8: webitel.cases.LocateStatusConditionRequest
	(*LocateStatusConditionResponse)(nil), // 9: webitel.cases.LocateStatusConditionResponse
	(*Lookup)(nil),                        // 10: general.Lookup
	(*wrapperspb.BoolValue)(nil),          // 11: google.protobuf.BoolValue
}
var file_status_condition_proto_depIdxs = []int32{
	10, // 0: webitel.cases.StatusCondition.created_by:type_name -> general.Lookup
	10, // 1: webitel.cases.StatusCondition.updated_by:type_name -> general.Lookup
	11, // 2: webitel.cases.InputStatusCondition.initial:type_name -> google.protobuf.BoolValue
	11, // 3: webitel.cases.InputStatusCondition.final:type_name -> google.protobuf.BoolValue
	0,  // 4: webitel.cases.StatusConditionList.items:type_name -> webitel.cases.StatusCondition
	3,  // 5: webitel.cases.CreateStatusConditionRequest.input:type_name -> webitel.cases.InputCreateStatusCondition
	1,  // 6: webitel.cases.UpdateStatusConditionRequest.input:type_name -> webitel.cases.InputStatusCondition
	0,  // 7: webitel.cases.LocateStatusConditionResponse.status:type_name -> webitel.cases.StatusCondition
	7,  // 8: webitel.cases.StatusConditions.ListStatusConditions:input_type -> webitel.cases.ListStatusConditionRequest
	4,  // 9: webitel.cases.StatusConditions.CreateStatusCondition:input_type -> webitel.cases.CreateStatusConditionRequest
	5,  // 10: webitel.cases.StatusConditions.UpdateStatusCondition:input_type -> webitel.cases.UpdateStatusConditionRequest
	6,  // 11: webitel.cases.StatusConditions.DeleteStatusCondition:input_type -> webitel.cases.DeleteStatusConditionRequest
	8,  // 12: webitel.cases.StatusConditions.LocateStatusCondition:input_type -> webitel.cases.LocateStatusConditionRequest
	2,  // 13: webitel.cases.StatusConditions.ListStatusConditions:output_type -> webitel.cases.StatusConditionList
	0,  // 14: webitel.cases.StatusConditions.CreateStatusCondition:output_type -> webitel.cases.StatusCondition
	0,  // 15: webitel.cases.StatusConditions.UpdateStatusCondition:output_type -> webitel.cases.StatusCondition
	0,  // 16: webitel.cases.StatusConditions.DeleteStatusCondition:output_type -> webitel.cases.StatusCondition
	9,  // 17: webitel.cases.StatusConditions.LocateStatusCondition:output_type -> webitel.cases.LocateStatusConditionResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_status_condition_proto_init() }
func file_status_condition_proto_init() {
	if File_status_condition_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_condition_proto_rawDesc), len(file_status_condition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_condition_proto_goTypes,
		DependencyIndexes: file_status_condition_proto_depIdxs,
		MessageInfos:      file_status_condition_proto_msgTypes,
	}.Build()
	File_status_condition_proto = out.File
	file_status_condition_proto_goTypes = nil
	file_status_condition_proto_depIdxs = nil
}
